Doxyfile.in
README.md

1. Updated links and disabled file list generation in Doxygen.
2. Added MACRO definition for stack allocation size.
Signed-Off-By: Alexander Damian <adamian@bloomberg.net>

Updated links and disabled file list generation in Doxygen.

---

README.md
src/quantum/quantum.h

Updated readme title to reflect C++ language

---

src/quantum/impl/quantum_stack_traits_impl.h
tests/quantum_fixture.h

Fixed inline directive and reduced coroutine stack size for testing

---

src/quantum/quantum.h

Updated main header file

---

src/quantum/impl/quantum_context_impl.h
src/quantum/impl/quantum_dispatcher_core_impl.h
src/quantum/impl/quantum_dispatcher_impl.h
src/quantum/interface/quantum_icoro_context.h
src/quantum/interface/quantum_ithread_context.h
src/quantum/quantum_context.h
src/quantum/quantum_dispatcher.h
src/quantum/quantum_dispatcher_core.h
tests/quantum_fixture.h
tests/quantum_tests.cpp

Also fixed an issue with the queue count in the stats method.

Added getters for the number of coroutine and IO threads

---

src/quantum/impl/quantum_io_queue_impl.h
src/quantum/quantum_io_queue.h

Removed separate thread servicing the shared queue and added alternate polling for regular threads.

Removed separate thread servicing the shared queue

---

src/quantum/impl/quantum_dispatcher_impl.h
src/quantum/quantum_dispatcher.h
tests/quantum_tests.cpp

Added `forEach()` and `forEachBatch()` functions which offer similar functionality as `std::for_each`.

Added parallel forEach functions

---

README.md
src/quantum/impl/quantum_dispatcher_impl.h
src/quantum/interface/quantum_ithread_context.h
src/quantum/quantum_context.h
src/quantum/quantum_dispatcher.h
src/quantum/quantum_dispatcher_core.h
tests/quantum_fixture.h
tests/quantum_tests.cpp

Aliased Dispatcher to TaskDispatcher

---

CMakeLists.txt
src/quantum/impl/quantum_context_impl.h
src/quantum/impl/quantum_dispatcher_core_impl.h
src/quantum/impl/quantum_dispatcher_impl.h
src/quantum/impl/quantum_future_joiner_impl.h
src/quantum/impl/quantum_promise_impl.h
src/quantum/impl/quantum_util_impl.h
src/quantum/interface/quantum_icontext_base.h
src/quantum/interface/quantum_icoro_context.h
src/quantum/interface/quantum_icoro_future.h
src/quantum/interface/quantum_icoro_promise.h
src/quantum/interface/quantum_ithread_context.h
src/quantum/interface/quantum_ithread_future.h
src/quantum/interface/quantum_ithread_promise.h
src/quantum/quantum.h
src/quantum/quantum_configuration.h
src/quantum/quantum_context.h
src/quantum/quantum_dispatcher.h
src/quantum/quantum_future.h
src/quantum/quantum_future_joiner.h
src/quantum/quantum_promise.h
src/quantum/quantum_util.h
tests/quantum_tests.cpp

* Added future joiner utility class
* Added aliases for ::Ptr typedefs
* Added optional timeout parameter to `Dispatcher::drain()`

Added future joiner utility class

---

src/quantum/interface/quantum_icoro_context.h
src/quantum/quantum.h

Added vector include statement

---

src/quantum/impl/quantum_context_impl.h
src/quantum/impl/quantum_dispatcher_impl.h
src/quantum/impl/quantum_io_queue_impl.h
src/quantum/impl/quantum_task_queue_impl.h
src/quantum/impl/quantum_util_impl.h
src/quantum/interface/quantum_icoro_context.h
src/quantum/quantum_context.h
src/quantum/quantum_dispatcher.h
src/quantum/quantum_functions.h
src/quantum/quantum_future_joiner.h
src/quantum/quantum_util.h

Added typedefs for the various forEach and mapReduce functions

---

src/quantum/impl/quantum_configuration_impl.h
src/quantum/quantum.h
src/quantum/quantum_configuration.h

Added JSON configuration schema

---

src/quantum/impl/quantum_configuration_impl.h

Added default values to schema

---

src/quantum/impl/quantum_task_queue_impl.h
tests/quantum_tests.cpp

Fixed iterator double increment issue

---

tests/sequencer_tests.cpp

Reduce the time spent on sequencer tests

---

src/quantum/impl/quantum_task_queue_impl.h

Clear blocked iterator when list is empty

---

src/quantum/impl/quantum_task_queue_impl.h

Clear blocked iterator if the blocked coroutine has finished

---

CMakeLists.txt

Allow for setting compile flags via CXXFLAGS env variable

---

.travis.yml
CMakeLists.txt
README.md
src/quantum/impl/quantum_context_impl.h
src/quantum/impl/quantum_dispatcher_core_impl.h
src/quantum/impl/quantum_dispatcher_impl.h
src/quantum/impl/quantum_future_impl.h
src/quantum/impl/quantum_io_queue_impl.h
src/quantum/impl/quantum_io_task_impl.h
src/quantum/impl/quantum_promise_impl.h
src/quantum/impl/quantum_shared_state_impl.h
src/quantum/impl/quantum_spinlock_impl.h
src/quantum/impl/quantum_task_impl.h
src/quantum/impl/quantum_task_queue_impl.h
src/quantum/quantum_context.h
src/quantum/quantum_heap_allocator.h
src/quantum/quantum_stack_allocator.h
tests/quantum_tests.cpp
tests/sequencer_tests.cpp

Support for travis CI and minor Clang compiler warning fixes.

---

README.md

Added build badge in README file

---

src/quantum/impl/quantum_configuration_impl.h
src/quantum/impl/quantum_context_impl.h
src/quantum/impl/quantum_dispatcher_core_impl.h
src/quantum/impl/quantum_dispatcher_impl.h
src/quantum/interface/quantum_icoro_context.h
src/quantum/interface/quantum_ithread_context.h
src/quantum/quantum_configuration.h
src/quantum/quantum_context.h
src/quantum/quantum_dispatcher.h
src/quantum/quantum_dispatcher_core.h
src/quantum/util/quantum_sequencer.h
src/quantum/util/quantum_sequencer_configuration.h
tests/quantum_coro_ranges.cpp

Added coroutine Any queue range

---

src/quantum/impl/quantum_configuration_impl.h
src/quantum/impl/quantum_context_impl.h
src/quantum/impl/quantum_dispatcher_core_impl.h
src/quantum/impl/quantum_dispatcher_impl.h
src/quantum/interface/quantum_icoro_context.h
src/quantum/interface/quantum_ithread_context.h
src/quantum/quantum_configuration.h
src/quantum/quantum_context.h
src/quantum/quantum_dispatcher.h
src/quantum/quantum_dispatcher_core.h
tests/quantum_coro_ranges.cpp

changed type of coro queueId range to int, made the range end inclusive

---

tests/quantum_fixture.h
tests/quantum_tests.cpp

* Added test for external promise. 
* Removed ITerminate RAII guard when deleting promises as it's no longer needed.

Added test for external promise.

---

quantum/impl/quantum_io_queue_impl.h
quantum/impl/quantum_task_queue_impl.h

Signal only when the first task is added

---

quantum/impl/quantum_context_impl.h
quantum/impl/quantum_dispatcher_impl.h
quantum/interface/quantum_icoro_context.h
quantum/quantum_context.h
quantum/quantum_dispatcher.h
quantum/util/impl/quantum_util_impl.h
quantum/util/quantum_util.h
tests/quantum_tests.cpp

Updated forEach() and forEachBatch() to take non-const parameters

---

quantum/util/impl/quantum_util_impl.h

Rethrowing forced_unwind exception.

---

CMakeLists.txt
quantum/impl/quantum_io_queue_impl.h
quantum/impl/quantum_task_queue_impl.h

Determine if GLIBCXX_USE_CXX11_ABI is used for std::list compatibility

---

quantum/impl/quantum_task_queue_impl.h

Set end iterator to first element of wait queue

---

quantum/impl/quantum_read_write_spinlock_impl.h
quantum/quantum.h
quantum/quantum_read_write_spinlock.h
tests/quantum_coro_ranges_tests.cpp
tests/quantum_sequencer_tests.cpp
tests/quantum_spinlocks_tests.cpp
tests/quantum_tests.cpp

RW lock implementation

---

CMakeLists.txt

Changed method to determine bitness

---

quantum/impl/quantum_task_queue_impl.h

Changed empty condition signal to be under queue lock

---

quantum/CMakeLists.txt

* Fixed install header paths. The current implementation would skip private header directories.
* Did a local installation and verified all headers are present.

Fixed header install paths

---

CMakeLists.txt
README.md
quantum/CMakeLists.txt

Added QUANTUM_EXPORT_PKGCONFIG and QUANTUM_EXPORT_CMAKE_CONFIG to control the creation of config files
Cmake build

Optionally generate configuration files

---

quantum/interface/quantum_iqueue.h

Added string.h header for memcpy
Compiled

Added string.h header for memcpy

---

quantum/impl/quantum_stl_impl.h
quantum/quantum_traits.h

Added support for compile-time determination of multiple function args
Compiled

Added support for multiple function arg types

---

quantum/quantum_traits.h

Added missing header file
Compiled

Added missing header

---

README.md

- updated readme documentation

Updated documentation to reflect function overloads for v1 and v2 apis

---

quantum/util/impl/quantum_generic_future_impl.h
quantum/util/quantum_generic_future.h
tests/quantum_tests.cpp

- Added default constructor to `GenericFuture` class.
- Compiled

Added default constructor for GenericFuture

---

.travis.yml

- Compile for c++17
- Update distro to `bionic`
Compiles for all three language versions

Updated travis file for c++17 and bionic distro

---

quantum/impl/quantum_spinlock_impl.h

* Fixed assert statement in `SpinLock::lock()`

Fixed assert statement in SpinLock::lock()

---

quantum/impl/quantum_mutex_impl.h
quantum/impl/quantum_read_write_mutex_impl.h
quantum/impl/quantum_read_write_spinlock_impl.h
quantum/impl/quantum_spinlock_impl.h
quantum/quantum_mutex.h
quantum/quantum_read_write_mutex.h
quantum/quantum_read_write_spinlock.h
quantum/quantum_spinlock.h
quantum/quantum_spinlock_traits.h
tests/quantum_locks_tests.cpp

Added support for DeferLock in Mutex and Spinlock classes

---

quantum/impl/quantum_coroutine_pool_allocator_impl.h

Ensure coroutine stack size is a multiple of page size

Ensure coroutine stack size is a multiple of page size

---

quantum/util/impl/quantum_generic_future_impl.h
quantum/util/quantum_generic_future.h

Added support for `Promise<T>` in the `GenericFuture` constructor. 

Added support for Promise in the GenericFuture constructor

---

quantum/util/impl/quantum_generic_future_impl.h
tests/quantum_generic_future_tests.cpp

Added compile test for the Proimse constructor

Added compile test for the Proimse constructor

---

quantum/interface/quantum_iqueue.h
quantum/quantum_io_queue.h
quantum/quantum_task.h
quantum/quantum_task_queue.h

*Issue number of the reported bug or feature request: #<number>*
Fix C++20 Building Issues.
No functionality change. Build and CI pass required.
Add any other context about your contribution here.

Fix C++20 problems
