bloomberg/quantum

- README.md
- src/quantum/impl/quantum_context_impl.h
- src/quantum/impl/quantum_future_impl.h
- src/quantum/impl/quantum_io_queue_impl.h
- src/quantum/impl/quantum_io_task_impl.h
- src/quantum/impl/quantum_promise_impl.h
- src/quantum/impl/quantum_shared_state_impl.h
- src/quantum/impl/quantum_stack_allocator_impl.h
- src/quantum/impl/quantum_stack_traits_impl.h
- src/quantum/impl/quantum_task_impl.h
- src/quantum/impl/quantum_task_queue_impl.h
- src/quantum/interface/quantum_iqueue.h
- src/quantum/quantum.h
- src/quantum/quantum_io_queue.h
- src/quantum/quantum_stack_allocator.h
- src/quantum/quantum_stack_traits.h
- src/quantum/quantum_task_queue.h
- src/quantum/quantum_traits.h
- tests/quantum_tests.cpp
- Added allocators for task lists
- Static assert for the number of allocated blocks
- Added overrides for coroutine stack traits via new `StackTraits` class.
- Provided default boost allocator for coroutine stacks.
- Ability to completely turn off stack allocations via __QUANTUM_USE_DEFAULT_ALLOCATOR macro
- Fixed `SharedState::setException` to return -1 instead of 0 so the dispatcher properly treats it as an error.
> Stack allocator enhancements

- src/quantum/impl/quantum_context_impl.h
- src/quantum/impl/quantum_contiguous_pool_manager_impl.h
- src/quantum/impl/quantum_future_impl.h
- src/quantum/impl/quantum_io_task_impl.h
- src/quantum/impl/quantum_promise_impl.h
- src/quantum/impl/quantum_task_impl.h
- src/quantum/quantum_contiguous_pool_manager.h
- tests/quantum_tests.cpp
Support for allocating a larger number of objects than 1.
Added stress test for the shared IO queue.
> Allocator chunk support

- src/quantum/impl/quantum_future_joiner_impl.h
- src/quantum/interface/quantum_icontext_base.h
- src/quantum/interface/quantum_icoro_context_base.h
- src/quantum/interface/quantum_icoro_future_base.h
- src/quantum/interface/quantum_icoro_sync.h
- src/quantum/interface/quantum_ipromise_base.h
- src/quantum/interface/quantum_iqueue.h
- src/quantum/interface/quantum_itask.h
- src/quantum/interface/quantum_itask_accessor.h
- src/quantum/interface/quantum_itask_continuation.h
- src/quantum/interface/quantum_ithread_context_base.h
- src/quantum/interface/quantum_ithread_future_base.h
- src/quantum/quantum_dispatcher.h
- src/quantum/quantum_future_joiner.h
- src/quantum/quantum_io_task.h
- src/quantum/quantum_task.h
- tests/quantum_tests.cpp
* Added typedefs for ptr types. 
* Refined the `FutureJoiner` class to allow the joined type to differ from the dispatcher type
> Added typedefs for ptr types. Refined the FutureJoiner class

- src/quantum/impl/quantum_future_joiner_impl.h
- src/quantum/impl/quantum_stl_impl.h
- src/quantum/impl/quantum_util_impl.h
- src/quantum/interface/quantum_icoro_promise.h
- src/quantum/interface/quantum_ithread_promise.h
- src/quantum/quantum_future_joiner.h
- src/quantum/quantum_promise.h
- src/quantum/quantum_yielding_thread.h
- tests/quantum_tests.cpp
* Use `FutureJoiner` inside `forEach`.
* Changed template parameter to be dependent on the future type rather than on the dispatcher type.
> Use FutureJoiner inside forEach 

- src/quantum/impl/quantum_util_impl.h
Use the known ```batchSize``` to atleast reserve the vector ```result```, so that we can save on re-allocation costs.
> Use known batch size to better optimize the array.

- src/quantum/impl/quantum_task_queue_impl.h
- src/quantum/quantum_task_queue.h
This was introduced by the previous commit and needs to be written in a slightly different way. The current issue is that when `std::prev()` is called, another thread could be posting a new coroutine which would get inserted before the next one in the chain (i.e. before `advance()` is called)
> Fix re-ordering of coroutines

- src/quantum/impl/quantum_buffer_impl.h
- src/quantum/impl/quantum_shared_state_impl.h
- src/quantum/interface/quantum_icoro_context.h
- src/quantum/interface/quantum_icoro_future.h
- src/quantum/interface/quantum_icoro_promise.h
- src/quantum/interface/quantum_ithread_context.h
- src/quantum/interface/quantum_ithread_future.h
- src/quantum/interface/quantum_ithread_promise.h
- src/quantum/quantum_buffer.h
- src/quantum/quantum_context.h
- src/quantum/quantum_future.h
- src/quantum/quantum_promise.h
- src/quantum/quantum_shared_state.h
- src/quantum/quantum_traits.h
- tests/quantum_tests.cpp
Simplified buffer type SFINAE argument.
Provided allocator template parameter to the `Buffer` class.
Fixed pass-by-value argument in test case. 
> Simplified buffer type SFINAE argument.

- src/quantum/quantum.h
- src/quantum/util/impl/quantum_sequencer_configuration_impl.h
- src/quantum/util/impl/quantum_sequencer_impl.h
- src/quantum/util/impl/quantum_sequencer_key_statistics_impl.h
- src/quantum/util/quantum_sequencer.h
- src/quantum/util/quantum_sequencer_configuration.h
- src/quantum/util/quantum_sequencer_key_statistics.h
- tests/sequencer_tests.cpp
Implementation of a simple task Sequencer based on sequence keys. Each posted task can be associated with one more more sequence keys. The Sequencer guarantees that given two tasks T1 and T2 associated with sets of keys S1 and S2 such that S1 and S2 have common keys and T1 was posted before T2, then T2 will be started only after T1 is finished.
> Using quantum dispatcher for sequencing tasks based on sequence key

- src/quantum/util/impl/quantum_sequencer_impl.h
- src/quantum/util/quantum_sequencer.h
- tests/sequencer_tests.cpp
Refactored `postEx` argument positions to avoid having two overloaded function names. This was done by moving the `void* opaque` to the front of the argument list. Because of this, the _Ex_ functions can now be renamed `post` just like the other ones. The original issue arose from the clash in type when `sequenceKey` was an `int`, therefore ADL would resolve it with the `queueId` parameter which was wrong.
> Refactored postEx argument positions 

- src/quantum/impl/quantum_context_impl.h
- src/quantum/impl/quantum_io_queue_impl.h
- src/quantum/impl/quantum_io_task_impl.h
- src/quantum/impl/quantum_task_impl.h
- src/quantum/impl/quantum_task_queue_impl.h
- src/quantum/interface/quantum_icoro_sync.h
- src/quantum/interface/quantum_itask.h
- src/quantum/interface/quantum_itask_accessor.h
- src/quantum/quantum_context.h
- src/quantum/quantum_io_task.h
- src/quantum/quantum_task.h
- src/quantum/quantum_task_queue.h
- src/quantum/quantum_thread_traits.h
- src/quantum/quantum_yielding_thread.h
- tests/quantum_tests.cpp
- tests/sequencer_tests.cpp
Changes to reduce CPU overload when a coroutine sleeps or is blocked. 
Added microsecond precision (in classes `ThreadTraits::yieldSleepIntervalUs()` and `ICoroSync::sleep()`) for coroutine sleeping as well as yielding a non-coroutine thread.
Fixed race conditions in Sequencer tests.
> Changes to reduce CPU overload when a coroutine sleeps or is blocked.

- src/quantum/util/impl/quantum_sequencer_configuration_impl.h
- src/quantum/util/impl/quantum_sequencer_impl.h
- src/quantum/util/quantum_sequence_key_statistics.h
- src/quantum/util/quantum_sequencer.h
- tests/sequencer_tests.cpp
* Fixed some minor issues with `Sequencer` class and also added stats for total tasks posted.
* Internal refactoring of some methods for simpler API.
* Decrement pending count before the task is scheduled to run as opposed to after. This makes statistics more indicative of reality.
> Fixed some minor issues with Sequencer class

- src/quantum/util/impl/quantum_sequencer_impl.h
- tests/sequencer_tests.cpp
Some variables we passed to dispatcher by references caused test failures (e.g. https://github.com/bloomberg/quantum/issues/45), so this PR fixes them. Plus, this fixes the SequenceKeyStats test by having a dispatcher-based wait for the first half tasks to be scheduled.
> Pass-by-reference fixes + minor fixes to SequenceKeyStats

- CMakeLists.txt
Allow more flexibility when setting the build environment. `CXXFLAGS` environment variable can be set to contain all compile options.
> Don't force -std=c++14 if not in CXXFLAGS

- src/quantum/impl/quantum_buffer_impl.h
- src/quantum/impl/quantum_context_impl.h
- src/quantum/impl/quantum_future_impl.h
- src/quantum/impl/quantum_promise_impl.h
- src/quantum/impl/quantum_shared_state_impl.h
- src/quantum/impl/quantum_stl_impl.h
- src/quantum/interface/quantum_icoro_context.h
- src/quantum/interface/quantum_icoro_future.h
- src/quantum/interface/quantum_icoro_promise.h
- src/quantum/interface/quantum_ithread_context.h
- src/quantum/interface/quantum_ithread_future.h
- src/quantum/interface/quantum_ithread_promise.h
- src/quantum/quantum.h
- src/quantum/quantum_buffer.h
- src/quantum/quantum_context.h
- src/quantum/quantum_future.h
- src/quantum/quantum_promise.h
- src/quantum/quantum_shared_state.h
- src/quantum/quantum_traits.h
- tests/quantum_tests.cpp
locking between readers and writers.
Added SFINAE for selection of Buffer vs Non-Buffer supported methods.
> Buffer class refactoring and performance improvement to avoid less

- src/quantum/impl/quantum_configuration_impl.h
- src/quantum/quantum_configuration.h
> Updated quantum schema with the queue range for 'any'.

- .travis.yml
- CMakeLists.txt
- src/CMakeLists.txt
- tests/CMakeLists.txt
Added default install directory for headers to avoid having to run 'make install' before building test target
> Added default install directory for headers.

- CMakeLists.txt
Headers will be installed prior to build directly into the CMAKE_INSTALL_PREFIX location.
> Removed temp install folder. 

- quantum/impl/quantum_condition_variable_impl.h
- quantum/impl/quantum_mutex_impl.h
- quantum/quantum_condition_variable.h
- quantum/quantum_mutex.h
Description:
- Added coroutine synchronization for ConditionVariable::notifyOne() and
ConditionVariable::notifyAll().
- Fixed Mutex locking so that coroutines yield instead of microsleeping
the current thread.
> Coroutine sync support in ConditionVariable

- quantum/impl/quantum_stl_impl.h
- quantum/interface/quantum_icoro_context.h
- quantum/quantum_dispatcher.h
- quantum/quantum_functions.h
- quantum/util/impl/quantum_sequencer_impl.h
- quantum/util/impl/quantum_util_impl.h
- quantum/util/quantum_sequencer.h
- quantum/util/quantum_util.h
- tests/quantum_tests.cpp
- tests/sequencer_tests.cpp
* Passing coroutine context into `forEach` and `mapReduce` with type `Void`.
* Changed `Sequencer` function signature to ignore context type since it was
not needed anyway.
> Passing coroutine context into forEach and mapReduce with type Void.

- quantum/impl/quantum_read_write_spinlock_impl.h
- quantum/quantum_read_write_spinlock.h
- tests/quantum_spinlocks_tests.cpp
Renamed `ReadWriteSpinlock` to `ReadWriteSpinLock` for consistency purposes with `SpinLock` class.
> Renamed ReadWriteSpinlock to ReadWriteSpinLock

- quantum/impl/quantum_stl_impl.h
Signed-off-by: Alex Damian <adamian@bloomberg.net>
> Fixed redefinition of reinterpret_pointer_cast when compiling with c++17

- quantum.pc.in
- quantum/impl/quantum_condition_variable_impl.h
- quantum/impl/quantum_context_impl.h
- quantum/impl/quantum_dispatcher_impl.h
- quantum/quantum_context.h
- tests/quantum_sequencer_tests.cpp
- tests/quantum_tests.cpp
**Description**
* Using steady_clock for all time interval measurements. 
* Fixed `boost-context` library name in .pc file.
> Using steady_clock for all time interval measurements. 

- quantum/impl/quantum_configuration_impl.h
- quantum/impl/quantum_dispatcher_core_impl.h
- quantum/impl/quantum_task_impl.h
- quantum/impl/quantum_task_queue_impl.h
- quantum/interface/quantum_itask.h
- quantum/quantum_configuration.h
- quantum/quantum_dispatcher_core.h
- quantum/quantum_task.h
- quantum/quantum_task_queue.h
- quantum/util/impl/quantum_util_impl.h
- tests/quantum_fixture.h
- tests/quantum_sequencer_tests.cpp
- tests/quantum_tests.cpp
*Issue number of the reported bug or feature request: #<number>*
Introducing the shared-any-coro-queue mode. When this feature is enabled, Dispatcher creates a dedicated Queue::QueueId::Any queue and a thread for processing tasks enqueued into it. All coroutine tasks enqueued with queueId = Queue::QueueId::Any will be pushed to that queue. Also each thread in the coroQueueIdRangeForAny range registers itself as a 'helper' for the Queue::QueueId::Any queue and executes tasks  from the Queue::QueueId::Any as well as tasks from its own queue.
Ran the existing tests and added a performance test for this mode.
Add any other context about your contribution here.
> Shared any-coro-queue changes

- quantum/impl/quantum_dispatcher_core_impl.h
- quantum/impl/quantum_io_queue_impl.h
- quantum/impl/quantum_task_queue_impl.h
- quantum/interface/quantum_iqueue.h
- quantum/quantum_dispatcher_core.h
- quantum/quantum_io_queue.h
- quantum/quantum_task_queue.h
* Rename quantum threads for easier debugging. Threads are named as follows:
[`quantum:` ]+ [`co:` or `io:`] + [`s:` or `a:`] + `num`
where `co` and `io` denote coroutine or async io threads. `s` and `a` denote `shared` and `any` threads for coroutines only.
* Removed deprecated private constructor
Validated under GDB
> Named threads in the quantum library

- quantum/impl/quantum_capture_impl.h
- quantum/impl/quantum_queue_statistics_impl.h
- quantum/quantum_capture.h
- quantum/quantum_contiguous_pool_manager.h
- quantum/util/impl/quantum_future_joiner_impl.h
- tests/quantum_fixture.h
- tests/quantum_sequencer_tests.cpp
- tests/quantum_spinlocks_tests.cpp
- tests/quantum_tests.cpp
* Fixed a small memory leak in the `Control` block of the `ContiguousPoolManager`
* Ensure that capture variable destructors are properly called in the `Function::~Function()` destructor. Previously only the buffer was freed which prevented captured variables from properly deleting their own members.
* Ensure that there are no underruns when decrementing the task counter.
* In the `Sequencer` tests, sped up creation and tear-down of the fixture by not having to create all the Dispatcher variations each time.
* Small changes to some test parameters to speed up when testing with Valgrind. 
Ran all GTESTs as well as ran under Valgrind to make sure the tool is not reporting any leaks.
> Fixed mem-leak and prevent underruns in stats counter

- README.md
- quantum/impl/quantum_context_impl.h
- quantum/impl/quantum_dispatcher_impl.h
- quantum/impl/quantum_stl_impl.h
- quantum/interface/quantum_icoro_context.h
- quantum/interface/quantum_ithread_context.h
- quantum/interface/quantum_ithread_promise.h
- quantum/quantum_dispatcher.h
- quantum/quantum_traits.h
- quantum/util/impl/quantum_future_joiner_impl.h
- quantum/util/impl/quantum_sequencer_impl.h
- quantum/util/impl/quantum_util_impl.h
- tests/quantum_tests.cpp
* Automatically deduce the return type for all callable objects passed to the library. This means that it is not longer required/needed to specify the return type as a template parameter when when posting jobs, making it easier and more intuitive. This applies to V1 and V1 APIs including `forEach` and `mapReduce` functions.
As an example:
```c++
auto ctx = dispatcher.postFirst<int>([](CoroContext<int>::Ptr ctx)->int {
return ctx->set(55); //declared type is int
})->then<double>([](CoroContext<double>::Ptr ctx)->int {
return ctx->set(22.33); //declared type is double
})->then<std::string>([](CoroContext<std::string>::Ptr ctx)->int {
return ctx->set("future"); //declared type is string …
```
> Deduce return type for all API invokable functions.

- quantum/quantum_traits.h
Added additional missing headers `memory` and `tuple` to compile on DTS-7
> Added missing memory and tuple headers

- quantum/quantum_dispatcher.h
- quantum/util/impl/quantum_sequencer_impl.h
- quantum/util/quantum_drain_guard.h
- quantum/util/quantum_sequencer.h
- tests/quantum_sequencer_tests.cpp
- tests/quantum_tests.cpp
Added a `drain()` member function to the `Sequencer` class which is identical in signature to `Dispatcher::drain()`. While draining can be done directly from the dispatcher object itself, there are situations when the jobs enqueued in the Sequencer may post additional sub-jobs in the `Dispatcher`. If the `Dispatcher` drains, these jobs would fail since posting is disallowed while draining. By draining the `Sequencer` we allow all jobs to complete successfully. 
Ran unit tests and replaced `Dispatcher::drain()` with `Sequencer::drain()`
> Added drain functionality to the Sequencer

- quantum/impl/quantum_context_impl.h
- quantum/impl/quantum_dispatcher_impl.h
- quantum/impl/quantum_io_task_impl.h
- quantum/impl/quantum_stl_impl.h
- quantum/impl/quantum_task_impl.h
- quantum/interface/quantum_icoro_context.h
- quantum/interface/quantum_ithread_context.h
- quantum/interface/quantum_ithread_promise.h
- quantum/quantum_context.h
- quantum/quantum_dispatcher.h
- quantum/quantum_io_task.h
- quantum/quantum_task.h
- quantum/quantum_traits.h
- quantum/util/impl/quantum_sequencer_impl.h
- tests/quantum_sequencer_tests.cpp
- tests/quantum_tests.cpp
- Using SFINAE and automatic return value type deduction, overload all the `post` member functions (`post, postAsyncIo, postFirst, then, onError, finally`) to accept both V1 and V2 API. The application is not longer required to explicitly call `post2` functions in order to run V2 API functions and can use a single overload instead. 
Example:
```c++
//V1 API
auto func1 = [](CoroContextPtr<std::string> ctx)->int { return ctx->set("HelloWorld!"); }
//V2 API
auto func2 = [](VoidContextPtr)->std::string { return "HelloWorld!"; }
Dispatcher d;
d.post(func1); //ok
d.post(func2); //ok (use overload)
d.post2(func2); //still ok (kept for backward compatibility)
```
_NOTE_: `forEach, forEachBatch, mapReduce, …
> Overload all post member functions for V1 and V2 API

- quantum/quantum.h
- quantum/quantum_cls.h
- quantum/util/impl/quantum_cls_guard_impl.h
- quantum/util/quantum_cls_guard.h
- tests/quantum_tests.cpp
1) Got rid of the exception throwing code in cls::variable by using thread_local when the function is called outside of a coroutine
2) Added cls::Guard for cls variable management.
Ran existing tests + added a test for cls::Guard.
Add any other context about your contribution here.
> cls variable improvements

- quantum/util/impl/quantum_generic_future_impl.h
- Fixed uninitialized union member in `GenericFuture`
> Fixed uninitialized union member

- quantum/impl/quantum_condition_variable_impl.h
Use mutable temporary duration for `ConditionVariable::waitFor()`. Otherwise API does not compile due to const qualifiers.
> Use mutable temporary duration for ConditionVariable::waitFor()

- quantum/impl/quantum_condition_variable_impl.h
- quantum/impl/quantum_dispatcher_impl.h
- quantum/interface/quantum_ithread_future_base.h
- quantum/quantum_condition_variable.h
- quantum/quantum_dispatcher.h
- quantum/util/impl/quantum_sequencer_impl.h
- quantum/util/quantum_sequencer.h
- Changed default infinite timeout to be `-1` instead of `0`. `0` behaves as if no timeout was specified i.e. times out immediately.
- Updated `ConditionVariable::waitFor()` to match more closely the STL behavior.
> Changed default infinite timeout to be -1 instead of 0. 

- quantum/impl/quantum_io_queue_impl.h
- quantum/impl/quantum_mutex_impl.h
- quantum/impl/quantum_promise_impl.h
- quantum/impl/quantum_read_write_mutex_impl.h
- quantum/impl/quantum_read_write_spinlock_impl.h
- quantum/impl/quantum_spinlock_impl.h
- quantum/impl/quantum_task_queue_impl.h
- quantum/quantum_mutex.h
- quantum/quantum_read_write_mutex.h
- quantum/quantum_read_write_spinlock.h
- quantum/quantum_spinlock.h
- quantum/quantum_spinlock_traits.h
- quantum/util/impl/quantum_spinlock_util_impl.h
- quantum/util/quantum_spinlock_util.h
- tests/quantum_locks_tests.cpp
Updated `ReadWriteSpinlock` to be atomically upgrade-able from Reader to Writer.
> Updated ReadWriteSpinlock to be atomically upgrade-able from Reader to

- quantum/impl/quantum_read_write_mutex_impl.h
- tests/quantum_locks_tests.cpp
Fixed a bug where ReadWriteMutex::tryUpgradeToWrite() did not properly set the write-lock owner, so unlockWrite() operations were asserting. Refined an existing assert to be easier to understand.
Added additional unit tests to verify this case.
> Correctly set writer in ReadWriteMutex::tryUpgradeToWrite(), add tests

- quantum/impl/quantum_read_write_mutex_impl.h
- quantum/impl/quantum_read_write_spinlock_impl.h
- quantum/impl/quantum_spinlock_impl.h
- quantum/quantum_read_write_mutex.h
- quantum/quantum_read_write_spinlock.h
- quantum/quantum_spinlock_traits.h
- quantum/util/impl/quantum_sequencer_impl.h
- quantum/util/impl/quantum_spinlock_util_impl.h
- quantum/util/quantum_spinlock_util.h
- tests/quantum_locks_tests.cpp
- tests/quantum_tests.cpp
**Description**
If `ReadWriteLock::upgradeToWrite()` was called and there were more than one simultaneous upgrades occurring, the function would block indefinitely. This was caused by the underlying loop calling `tryUpgradeToLock()` not keeping upgrade state during iterations. 
This fix introduces a new overload `ReadWriteSpinlock::tryUpgradeToWrite(bool& pendingUpgrade)` which should be used if calling this in a loop. 
The previous tests only covered calling `ReadWriteSpinlock::upgradeToWrite()` which worked properly because it was not invoked inside a loop. The `ReadWriteMutex::upgradeToWrite()` calls it in a loop which was never actually tested. As a validation, running the new added test on the previous master branch blocks indefinitely which proves the fix is …
> ReadWriteLock upgradeToWrite fix for simultaneous upgrades.

- quantum/impl/quantum_context_impl.h
- quantum/quantum_dispatcher.h
- quantum/quantum_traits.h
- quantum/util/impl/quantum_sequencer_impl.h
- quantum/util/impl/quantum_util_impl.h
- tests/quantum_sequencer_tests.cpp
- tests/quantum_tests.cpp
Ensure proper catch/rethrow of coroutine unwind exceptions
Normal test suite
> Catch and rethrow all stack unwind exceptions

- .travis.yml
- CMakeLists.txt
- quantum/util/impl/quantum_spinlock_util_impl.h
- quantum/util/quantum_spinlock_util.h
- tests/quantum_locks_tests.cpp
- Fix compiler optimizations and minor bugs caused by using -03
- Updated travis to build with RelWithDebInfo instead of Debug
**Notable bugs found**
- On `quantum_spinlock_util_impl.h:329` in `spinWaitWriter()` the closing parenthesis was in the wrong place.
-  In `lockRead, lockWrite and upgradeToWriteImpl` the check for `spinWaitReader` and `spinWaitWriter` was checking against `!= Attempt::Once` instead of `==Attempt::Unlimited`. When upgrading coroutines to write, the attempt is set to `Attempt::Reentrant` which was causing the coroutine to enter this spinwait loop. Since this spin wait loop does not yield the coroutine, the first coroutine being upgraded would take the lock, waiting for all other coroutine readers to either upgrade or release their read …
> Prevent some compiler optimizations

- quantum/impl/quantum_queue_statistics_impl.h
- quantum/interface/quantum_iqueue_statistics.h
- quantum/quantum_queue_statistics.h
- quantum/util/impl/quantum_sequencer_impl.h
- Ensure sequencer returns success when running tasks
- Fix small printing error when displaying dispatcher stats
> Ensure sequencer returns success when running tasks

- quantum/impl/quantum_coroutine_pool_allocator_impl.h
- quantum/impl/quantum_task_queue_impl.h
- quantum/quantum_coroutine_pool_allocator.h
- quantum/quantum_dispatcher_core.h
- tests/quantum_sequencer_tests.cpp
- Use MMAP instead of heap for coroutine allocations
- Moved header block at the end of the stack
The motivation behind using `mmap()` on Linux (and the equivalent feature on Windows - not yet supported) is to allow for immediate memory reclaiming of the coroutine stack (quite large). If heap allocations are used, although the allocated memory is freed, the dynamic memory management algorithm will not return immediately these blocks to the system as they may be reused at a later date (for obvious performance reasons). If the system is very busy, these blocks may become fragmented and new coroutine stack allocations will again require further expansion from system memory (via sbrk() or mmap()) as large contiguous areas won't be necessarily available. The result is …
> Alloc with MMAP

- quantum/util/impl/quantum_generic_future_impl.h
- tests/quantum_generic_future_tests.cpp
Fix validity check on generic futures when they are default constructed
> Fix validity check on generic futures when they are default constructed

- quantum/impl/quantum_configuration_impl.h
- quantum/quantum_configuration.h
- quantum/util/impl/quantum_sequencer_configuration_impl.h
- quantum/util/quantum_sequencer_configuration.h
- Added json schema for `Sequencer` configuration. 
- Moved schema getters into base classes `ConfigurationSchemaProvider` and `SequencerConfigurationSchemaProvider`
- Return reference to self for easier chaining when using config setters.
> Added json schema for the sequencer configuration

- quantum/quantum_macros.h
Signed-off-by: Adam M. Rosenzweig <arosenzweig3@bloomberg.net>
Remove the DEPRECATED macro, which was causing conflicts in downstream libraries and/or applications which linked in `quantum` and also other code which referenced `DEPRECATED` (for other purposes).
As quantum is not using these macros at all, I have chosen to remove them rather than rename them.
Verified that `quantum` builds, all tests still pass, and that all of our internal tasks & libraries that depend on `quantum` build successfully with the change.
> Rename DEPRECATED macro

- quantum/quantum_task.h
Signed-off-by: Albert Dang <adang2@bloomberg.net>
*Issue number of the reported bug or feature request: #<number>*
A clear and concise description of the changes you have made.
atomic header missing in quantum_task.h which caused build failure with c++ 20.
Describe the testing you have performed to ensure that the bug has been addressed, or that the new feature works as planned.
Add any other context about your contribution here.
> Add missing atomic header to quantum_task.h

- quantum/quantum_task.h
In `gcc-12`, a new warning triggers when an inappropriate `std::memory_order` is passed to an atomic function. Corrected `std::memory_order_acq_rel` to `std::memory_order_release` for the `store()` calls.
Testing limited to running CI.
No additional context.
> Use std::memory_order_seq_cst for store()

- .travis.yml
- quantum/util/impl/quantum_sequencer_experimental_impl.h
- quantum/util/impl/quantum_sequencer_impl.h
- quantum/util/quantum_sequencer.h
- quantum/util/quantum_sequencer_experimental.h
- tests/quantum_sequencer_experimental_tests.cpp
- tests/quantum_sequencer_tests.cpp
We identified an issue with the `experimental::Sequencer` where enqueueing a task with a duplicate sequenceKey (i.e. enqueuing with ["key1", "key1"]) would result in the enqueued task never beginning, and also blocking any subsequent tasks enqueued on that key.
Fixed by creating a `set` from the `vector` of sequenceKeys to de-dupe. Then explored the behavior of the non-experimental `Sequencer`, and fixed a similar issue, as well as incorrect statistics in the multiple sequenceKey case, even without duplicate keys.
Added new unit tests for both implementations of `Sequencer`, which ran to demonstrate the problem, and then applied the fix and demonstrated that the unit test now passes. Example from the `experimental::Sequencer` test:
``` …
```
> Fix error where duplicate sequenceKeys result in job not executing
